version: "3"
services:
  app:
    image: recipe-app-api
    build: .
    ports:
      - 8000:8000
    volumes: 
      - .:/code
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000" 
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=supersecretpassword
    depends_on:
      - db
  
  db:
    image: postgres:14.0-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword 